name: GitHub Actions Demo
on:
  release:
    types: [published]
jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_MUM_DEV_CODEBUILD_IAM_ROLE}}
          aws-region: us-east-1
      - name: "AWS CodeBuild run build"
        uses: aws-actions/aws-codebuild-run-build@v1
        env:
          AWS_REGION: ap-south-1
        with:
          project-name: test-app-codebuild-web-app-codebuild-web-app
