name: GitHub Actions Demo
on: [release]
permissions:
  id-token: write
  contents: read
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::757184591234:role/test-app-iam-web-app
          aws-region: ap-south-1
      - name: "AWS CodeBuild run build"
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: test-app-codebuild-web-app
